### ISSUE TITLE
Is reporting the model diff supported?

### ISSUE THREAD

**Issue by erksch** [OpenMined/KotlinSyft#197]
## Question

Hey there! Thanks for the awesome work on the Android front!

The demo works for training on the dataset but I can not see any code that is related to actually reporting the model diff to PyGrid. Is this already in the demo, or even supported by the library? 

Regards

**Comment by vkkhare** [comment]
Hi @erksch reporting the diffs to pygrid is not yet functional. It should be fairly easy to add though. We have plans to add it just haven't implemented it.

**Comment by vkkhare** [comment]
If you need it on priority, you can do it without altering the kotlin code. Just create a plan by pysyft that evaluates the diff between two sets of tensors. You can then serialise this diff and send it to pygrid by the report function already present in SyftJob.

**Comment by erksch** [comment]
Thank you for your quick response!
What do you mean by not altering the kotlin code? I would say I'd need to calculate the diff somehow like this example in python:
```python
diff = [ model_params[i] - updated_model_params[i] for i in range(len(model_params)) ]
diff_state = State(
    owner=hook.local_worker,
    state_placeholders=[PlaceHolder().instantiate(param) for param in diff]
)
diff_data = serialize(diff_state)
```
And then send a websocket message from type "federated/report" with the base64 encoded diff data.

**Comment by erksch** [comment]
I guess the main question would be how to subtract two SyftTensors.
```Kotlin
fun trainingProcess(...) {
  var diffState = model.modelState!!

  ... training goes here ....

  var updatedState = model.modelState!!
  for (i in 0..updatedState.syftTensors.size) {
    diffState.syftTensors[i] = diffState.syftTensors[i].subtract(updatedState.syftTensors[i])
  }
  mnistJob.report(diffState)
}
```
Since there seems to be no subtraction implementation maybe we should try it one float array level.

**Comment by erksch** [comment]
Okay this is what I came up with

```Kotlin
fun trainingProcess(...) {
  var originalState = model.modelState!!

  ... training goes here ....
  
  val diffTensors = mutableListOf<SyftTensor>()
  val newState = model.modelState!!

  for (i in 0..originalState.syftTensors.size) {
    val originalTensor = originalState.syftTensors[i].getTorchTensor()
    val originalFloats = originalTensor.dataAsFloatArray

    val newTensor = newState.syftTensors[i].getTorchTensor()
    val newFloats = newTensor.dataAsFloatArray

    val diffFloats = FloatArray(originalFloats.size)

    for (j in 0..originalFloats.size) {
      diffFloats[j] = originalFloats[i] - newFloats[i]
    }

    val diffTensor = Tensor.fromBlob(diffFloats, originalTensor.shape())
    val diffSyftTensor = SyftTensor.fromTorchTensor(diffTensor)
    diffTensors.add(diffSyftTensor)
}

val diffState = State(newState.placeholders, diffTensors)
mnistJob.report(diffState)
```

**Comment by vkkhare** [comment]
I actually wrote a method to evaluate a diff in Kotlin amd it is quite similar to what you came up with. It's left commented in SyftModel because of slow speed.

https://github.com/OpenMined/KotlinSyft/blob/dev/syftlib/src/main/java/org/openmined/syft/proto/SyftModel.kt#L40

The problem of writing this in Kotlin is we have sequentially iterate over all the indices and subtract them manually. This is way too slow if the model parameters' dimensions explode. There are few vectorization alternatives in Java like Bigdecimal but they only handle integer in substraction. 
The only way I could find to have a highly parallelized implementation while being able to support all the syft tensor types was doing that via a `diff` plan. Yet another issue with such type casting is the possibility of memory overflow when upcasting float16 to float64 or byte to int

**Comment by erksch** [comment]
Okay, I see the problem, I didn't really think of performance yet. This stuff is much easier in python :D 
If you already have some code in mind for creating a diffing plan it would be awesome to share a small notebook or add it somewhere in the repo.

**Comment by vkkhare** [comment]
Crudely, I would go about the lines of how a usual plan is implemented just removing all the custom arguments from it. https://github.com/OpenMined/PySyft/blob/v0.2.5/examples/experimental/FL%20Training%20Plan/Create%20Plan.ipynb

```python

@sy.func2plan(args_shape=args_shape)
def diff_plan(*model_params):   # we can also feed in two lists if torchscript supports
    num_params = len(model_params)/2
    old_params = model_params[:num_params]
    new_params = model_params[num_params:]
    diff = [new - old for old,new in zip(old_params,new_params)]
    return (
        *diff
    )
```

**Comment by erksch** [comment]
Ah right, I thought the plan function would also include reporting the diff to the grid but this could just be done in Kotlin.

**Comment by vkkhare** [comment]
But looking at this, I feel it cannot be a static file after all and we would need to generate this plan based on the model.

**Comment by erksch** [comment]
Why couldn't it be a static file? Looks good to me?

**Comment by vkkhare** [comment]
The `@sy.func2plan` requires the shape of arguments as input which varies tensor to tensor.

**Comment by vkkhare** [comment]
@erksch in any case, loading a diff plan and evaluating diff seems to be constant. I would move with that and we can later decide where the plan will come from.

**Comment by vkkhare** [comment]
So I looked into pysyft compatibility for args https://github.com/OpenMined/PySyft/blob/v0.2.5/examples/tutorials/Part%2008%20-%20Introduction%20to%20Plans.ipynb

@erksch Are you upto this? We can go via static file path with this

**Comment by erksch** [comment]
Nice I'll give it a try later.

**Comment by vkkhare** [comment]
@all-contributors add @erksch for creating an issue

**Comment by vkkhare** [comment]
@all-contributors fine add @erksch for creating a bug 😅😅

**Comment by vkkhare** [comment]
@all-contributors add @erksch for bugs

**Comment by erksch** [comment]
Hey @vkkhare sorry for the delay! I'll totally get back to you and the kotlin worker but I am a little bit occupied at the moment and I hope I can get back to it next week.

**Comment by vkkhare** [comment]
Oh okay no problem. Thanks @erksch!
