### ISSUE TITLE
Fix README.md typo

### ISSUE THREAD

**Issue by galalen** [OpenMined/KotlinSyft#204]
## Where?
[KotlinSyft/blob/dev/README.md](https://github.com/OpenMined/KotlinSyft/blob/dev/README.md)

## Who?
Any developer who wants to work on KotlinSyft should be able to read inline documentation for this file, as well as any file in the project.

## What?
Fix a typo in README me, when instantiating a `Sytf` object and using that object to create a new `SytfWorker`, the object used is different.

## Additional Context
None.

**Comment by vkkhare** [comment]
Closed via #201
