### ISSUE TITLE
Extract library versions to a separate Kotlin file

### ISSUE THREAD

**Issue by mccorby** [OpenMined/KotlinSyft#21]
We can have the versions of the library we use in a separate file to avoid confusions.

**Comment by IamRavikantSingh** [comment]
I would like to work on this issue.
Please give some extra information about the issue.

**Comment by vkkhare** [comment]
sure @IamRavikantSingh. Let me know if you have some doubts!

**Comment by IamRavikantSingh** [comment]
should I use the already existing gradle.properties file or create a new file. if new file what should I name it?

**Comment by vkkhare** [comment]
you should create a new properties file named `dependencyVersions.properties`. Also, make sure you have a common variable for dependencies that require the same version

**Comment by vkkhare** [comment]
There is a [better way](https://proandroiddev.com/treat-your-build-files-as-you-treat-your-code-def80ac52978) to use `dependency.gradle` This way we can also organize dependencies into clusters.

So I would recommend you segregate the dependencies into clusters and have their versions defined as variables. If we need we can move the version variables into new file.

**Comment by mccorby** [comment]
We could actually put the versions in a Kotlin file.

**Comment by mccorby** [comment]
https://github.com/OpenMined/AndroidWorker/blob/dev/buildSrc/src/main/java/Dependencies.kt

**Comment by IamRavikantSingh** [comment]
This issue can be closed

**Comment by vkkhare** [comment]
#49 closes this
