### ISSUE TITLE
Syft keeps trying to connect indefinitely if network error

### ISSUE THREAD

**Issue by mccorby** [OpenMined/KotlinSyft#221]
## Description
If Syft cannot connect to the server, it keeps trying indefinitely draining unnecessary resources.

## How to Reproduce
1. Set a wrong URL server in the initial screen
2. Start cycle
3. Observer logs

## Expected Behavior
Syft should stop retrying after certain amount of time.

## System Information
 - OS Version: [e.g. 22]
 - Language Version: [e.g. Python 3.7, Node 10.18.1]
 - Package Manager Version: [e.g. Conda 4.6.1, NPM 6.14.1]
 - Browser (if applicable): [e.g. Google Chrome]
 - Browser Version (if applicable): [e.g. 81.0.4044.138]

**Comment by vkkhare** [comment]
Connected to #20
