### ISSUE TITLE
Scaffold basic proposed worker API in Android

### ISSUE THREAD

**Issue by vkkhare** [OpenMined/KotlinSyft#23]
The following is the proposed worker API in syft.js: https://github.com/OpenMined/Roadmap/blob/master/web_and_mobile_team/projects/federated_learning.md#4-execute

I propose that we have a nearly identical API for Android.

**Comment by mccorby** [comment]
It will be also the entry point to any client using the library.
Syft will coordinate the different aspect of the solution.
