### ISSUE TITLE
Namespace static FL routes

### ISSUE THREAD

**Issue by sachin-101** [OpenMined/KotlinSyft#238]
## What?
Please, add prefix `/model_centric` to all the requests to grid. You can also get rid of the unnecessary `/federated` for all endpoints that have it as part of the url. Part of an effort to namespace static and dynamic API routes in PyGrid. 
#https://github.com/OpenMined/PyGrid/issues/600

Reference to PyGrid PR: https://github.com/OpenMined/PyGrid/pull/622

**Comment by vkkhare** [comment]
So essentially it becomes `/static/federated/...`

**Comment by sachin-101** [comment]
Yups.. @vkkhare, but we will move to if after your demo with the Pytorch team.
