### ISSUE TITLE
We've been rejected for the time

### ISSUE THREAD

**Issue by pengyuan-zhou** [OpenMined/KotlinSyft#241]
Hi all,
I've tried  run the demo for two days, some times it could some times failed, I haven't found out the reasons.
The following is the major failure, which I met in both the cases of using local AVD and android phone.
After "Start foreground", the client (if using AVD) log the following:
```
2020-07-18 02:03:09.088 10954-11012/org.openmined.syft.demo D/NetworkStateEvaluator: Download Speed is 15456.6045 KBps
2020-07-18 02:03:10.161 10954-11012/org.openmined.syft.demo D/NetworkStateEvaluator: Upload Speed is 100000.0 KBps
```
then immediately stuck with "We've been rejected for the time".

Any suggestion is appreciated.
Thanks :)

**Comment by vkkhare** [comment]
Hi @pengyuan-zhou this is not a bug. PyGrid accepts the worker for the max number specified by the user. This simply means that the worker was rejected by pygrid. To configure this parameter look for server config in the creat plan notebook

**Comment by pengyuan-zhou** [comment]
Aha, problem solved, thank you!
