### ISSUE TITLE
HTTP 401 UNAUTHORIZED

### ISSUE THREAD

**Issue by aghia98** [OpenMined/KotlinSyft#282]
## Question
**When trying to use the App Demo with PyGrid Server, I am getting an HTTP 401 error UNAUTHORIZED**

## Further Information
I disabled authentication in pygrid so as I don't need using private key/auth_token 

## Screenshots
[https://ibb.co/TKpcBvK](url)

## System Information
 - OS: Windows 10
 - OS Version: v2004
 - Emulator Android Studio
 - PyGrid Server

**Comment by aghia98** [comment]
correct screenshot link: ibb.co/TKpcBvK

**Comment by vkkhare** [comment]
Hi @aghia98 you might also need to supply empty auth token in demo app. Currently it gives a JWT compatible with private key. Am assuming the pygrid doesn't have a key added while hosting in the notebook

**Comment by aghia98** [comment]
Hi, this issue was fixed. The problem was that the model version hosted in pygrid was "1.0" while it was coded as "1.0.0" in kotlinsyft client.
Thanks
