### ISSUE TITLE
There is no model-centric directory in PyGrid commit 0e93aa645a63a02f45ae72b4ff3106c6402dbadf

### ISSUE THREAD

**Issue by zzaebok** [OpenMined/KotlinSyft#288]
## Question
I cannot find model-centric in commit 0e93aa645a63a02f45ae72b4ff3106c6402dbadf

## Further Information
I followed running demo-app part.
I cloned PyGrid and checkout to 0e93aa645a63a02f45ae72b4ff3106c6402dbadf.
And there is no model-centric directory in examples.
Could you check it please?

## Screenshots
![Screenshot from 2020-12-02 16-20-10](https://user-images.githubusercontent.com/44357534/100841284-6b148380-34ba-11eb-8654-ceea92570206.png)

## System Information
 - OS: ubuntu
 - OS Version: 18.04
 - Language Version: Python 3.7

**Comment by vkkhare** [comment]
@zzaebok it's in PySyft not PyGrid. Here is the [link](https://github.com/OpenMined/PySyft/tree/9d4f8e3ebecc4a00428607403832c5628753f1fc/examples/tutorials/model-centric-fl)

**Comment by zzaebok** [comment]
@vkkhare Oh my god, I am so sorry about it.
