### ISSUE TITLE
Find a better name for KTensor

### ISSUE THREAD

**Issue by galalen** [OpenMined/KotlinSyft#296]
## Description
KTensor is implemented in [dataloader API](https://github.com/OpenMined/KotlinSyft/pull/291), it's just a data holder that contains **shape** and **data** will help in construct IValue which is used by torch mobile. We're discussing rename it to SyftTensor if the name wouldn't be used for something else.

## Additional Context
Add any other context or screenshots.

**Comment by vkkhare** [comment]
this issue aligns with a larger issue #214

**Comment by galalen** [comment]
> this issue aligns with a larger issue #214

For this one, we can just use torch mobile Tensor class

**Comment by galalen** [comment]
KTensor is no longer used in the data loader API.
