### ISSUE TITLE
Debugging Torchscript / Plans in Android

### ISSUE THREAD

**Issue by mustansarsaeed** [OpenMined/KotlinSyft#297]
Hi,
Thank you for the great APIs. I am just worried how can we debug `Plans` that we have downloaded as `Binary` from `PyGrid` server. e.g., I am executing training plan as follows:

**Training plan Android**
```
val output = plan.execute(
                            batchData.first,
                            batchData.second,
                            batchIValue,
                            lr, paramIValue
                        )
```

How can we debug what's going on during the training?

Thanks.

**Comment by vkkhare** [comment]
Hi @mustansarsaeed debugging is not possible in android devices at the moment for tensor computations. THese are the few options to debug:

- Debug plan generating functions. When building the plan the ops are separate so you can use any python debugger over there on a dummy dataset.
- break the plans into multiple pieces and execute each one independently. Maybe we will support this kind of debugger on the android emulator for testing purposes. But this test suite is far into the development pipeline
- you can extract the torchscript out of the binary file and use that `.pt` file on any pytorch/python debugger if it exists
