### ISSUE TITLE
Implement Protobuf classes in Android

### ISSUE THREAD

**Issue by cereallarceny** [OpenMined/KotlinSyft#30]
We need to add the following Protobuf classes to KotlinSyft as they are completed:
- [x] `Plan`
- [x] `State`
- [x] `Operation`
- [x] `Placeholder`
- [x] `TorchParameter`
- [ ] ~`Protocol`~
- [ ] ~`PromiseTensor`~

## Stories associated to this epic:
- [x] Infrastructure #43

**Comment by vkkhare** [comment]
@all-contributors add @mccorby  for doing tests
