### ISSUE TITLE
How do I open this project in Android Studio?

### ISSUE THREAD

**Issue by tushar-semwal** [OpenMined/KotlinSyft#303]
## Where?
Where are you looking to add documentation? Which file? Which feature?
Getting started using Android Studio
## Who?
Who is your audience for this documentation issue?
Developers
## What?
Describe what you would like this documentation to accomplish.
Simple steps for beginners

**Comment by vkkhare** [comment]
Just open android studio, go to new project from VCS and enter the URL of the KotlinSyft repo
