### ISSUE TITLE
Allow for training state to be persisted to temporary storage in the event of a failure in Android

### ISSUE THREAD

**Issue by cereallarceny** [OpenMined/KotlinSyft#34]
In the event that training is interrupted on a device, we need to have a "saved state" of the training process that allows us to resume. Such interruptions could be:

- An error in the training
- User picks up their phone and begins using it
- Wifi connection drops
- Phone is unplugged

**Comment by vkkhare** [comment]
This essentially means we open up a function to store model weights in a `.pb` file. All we need to do is call the `State.protobuf_builder` , create the state protobuf and write a model_params.pb file. The user of the lib can then just call this method to save a checkpoint.

This method should be defined in `SyftModel`

**Comment by cereallarceny** [comment]
Closing in favor of https://github.com/OpenMined/KotlinSyft/issues/264
