### ISSUE TITLE
Implement sleep/wake detection demo in Android

### ISSUE THREAD

**Issue by cereallarceny** [OpenMined/KotlinSyft#36]
While we want to allow the end-user developer integrating KotlinSyft into their application the ability to choose to execute models while the user is asleep, we don't want to force them into this paradigm.

This issue includes developing a basic "asleep or awake" algorithm that a developer can choose to use. It's worth noting that the default option for a syft client would be to "enable" this as a requirement for training. It's up to the developer to state that they want this option "disabled".

**Comment by vkkhare** [comment]
Blocked until #87 is done
