### ISSUE TITLE
Update the endpoints and listener API according to roadmap

### ISSUE THREAD

**Issue by vkkhare** [OpenMined/KotlinSyft#47]
The new API provides a list of training plans and protocols. Update this in the data model of [CycleAccept](https://github.com/OpenMined/KotlinSyft/blob/dev/syftlib/src/main/java/org/openmined/syft/networking/datamodels/CycleResponseData.kt)

There are changes in the naming of subscriber methods for syft worker. They too need to be changed

**Comment by IamRavikantSingh** [comment]
I would like to work on this issue.
