### ISSUE TITLE
Write unit tests for the syftlib

### ISSUE THREAD

**Issue by vkkhare** [OpenMined/KotlinSyft#56]
With the new subscriber pattern being used everywhere, old tests were no longer valid. We need to rewrite the tests for library.
these class tests need to be written for this issue to finish

- [x]  JobStatusSubscriber

- [x] SocketClient

- [ ] WebRTC Client

- [ ] WebSocketClient

- [ ] DeviceMonitor

- [ ] Plan

- [ ] SyftJob

- [ ] ResponseRequestType

**Comment by cereallarceny** [comment]
Closing this issue in favor of #96
