### ISSUE TITLE
Add download/upload speed checker

### ISSUE THREAD

**Issue by vkkhare** [OpenMined/KotlinSyft#61]
We need to implement the functions `getDownloadSpeed`, `getUploadSpeed` and ping checker in `syft.kt`

**Comment by Avilad0** [comment]
Hey!! I am a gsoc applicant and I am trying to add this feature. Any additional information you would want me to solve

**Comment by vkkhare** [comment]
Hi @Avilad0. Welcome! There are three functions defined in `syftlib/src/main/java/org.openmined.syft/syft.kt` https://github.com/OpenMined/KotlinSyft/blob/aa055ed3458da24831ce948101d0a2a75d1c72af/syftlib/src/main/java/org/openmined/syft/Syft.kt#L129  namely getPing, getDownloadSpeed and getUploadSpeed. You need to get these values from pygrid endpoint defined [here](https://github.com/OpenMined/PyGrid/issues/445) under connection speed test

**Comment by vkkhare** [comment]
Also #58 might be easier for the first issue

**Comment by Avilad0** [comment]
i tried running the demo app but it just shows a start button which does nothing on clicking is there any error in what i installed
![Screenshot_2020-03-22-20-31-26-555_org openmined syft demo 1](https://user-images.githubusercontent.com/49166184/77252809-608fc200-6c7c-11ea-892f-28947a2d9d79.jpg)

**Comment by vkkhare** [comment]
Check the console output in android studio for debug messages. You should see the network requests being sent to pygrid. Also please use the #63 PR code. It will soon be merged. Currently demo app only does training in the background. #63 has the relevant code for establishing connection to pygrid

**Comment by Avilad0** [comment]
I/ConfigStore: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasWideColorDisplay retrieved: 0
    android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasHDRDisplay retrieved: 0
I/OpenGLRenderer: Initialized EGL, version 1.4
D/OpenGLRenderer: Swap behavior 2
**E/LB: fail to open file: No such file or directory**


//how to fix this ?

**Comment by vkkhare** [comment]
I merged the PR. Which android version are you using and which mobile?

**Comment by Avilad0** [comment]
I am using redmi note 7 pro android 9 , it is now showing socket error while running with the same above error.

**Comment by vkkhare** [comment]
For socket error, you need to follow these steps to setup pygrid as well (Bear with me for the long procedure):
1. clone the repo `https://github.com/OpenMined/PyGrid`
2. `cd Pygrid`
3. install docker https://github.com/OpenMined/PyGrid/#getting-started
4. install docker-compose
5. run `docker-compose up`
6. clone the repo `https://github.com/OpenMined/PySyft`
7. cd `Pysyft`
8. `virtualenv -p python3 venv`
9. `make venv`
10. `make notebook`
11. go to `http://localhost:8888/`
12. in the jupyter notebook,navigate to `examples/experimental/FL Training Plan`
13. Run the notebooks `createplan`. It should save three files in the `FL Training Plan` folder
14. Run the notebook `Host Plan`. Now the Pygrid is setup and the model is hosted over it.
15. The android app connects to your PC's localhost  via router (easier approach)
16. Get the IP address of your PC by running `ip address show | grep "inet " | grep -v 127.0.0.1` if using Linux. For windows there are different steps.
17. Fill the ip address [here](https://github.com/OpenMined/KotlinSyft/blob/dev/demo-app/src/main/java/org/openmined/syft/demo/ui/MainActivity.kt#L30)

**Comment by mccorby** [comment]
If you want to run it in the emulator use the address `10.0.2.2:5000`.

**Comment by Avilad0** [comment]
cant install docker as i dont have windows pro. i will see if there is another way. thanks for the time @vkkhare  @mccorby

**Comment by vkkhare** [comment]
You can run docker without having windows pro according to this [thread](https://forums.docker.com/t/installing-docker-on-windows-10-home/11722/5). Maybe @vvmnnnkv can help here
